package com.example.exercise10.work

const val PROGRESS_UPDATE_ACTION = "PROGRESS_UPDATE_ACTION"
const val PROGRESS_KEY_SERVICE = "PROGRESS_KEY_SERVICE"
const val PROGRESS_KEY_INTENT = "PROGRESS_KEY_INTENT"
const val MAX_VALUE = 100